---

# tasks file for roles/grafana

- name: install gpg
  apt:
    name: gnupg,software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: add gpg hey
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: no

- name: add repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"             
    state: present
    validate_certs: no

- name: install grafana
  apt:
    name: grafana
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: start service grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: wait for service up
  uri:
    url: "http://localhost:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1


- name: Configure Grafana for Subpath
  blockinfile:
    path: /etc/grafana/grafana.ini
    marker: "; Ansible Managed Block - Subpath Configuration"
    block: |
      [server]
      root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
      serve_from_sub_path = true
  notify:
    - restart_grafana

- name: Enable Nginx site configuration
  file:
    src: /etc/nginx/sites-available/wordpress
    dest: /etc/nginx/sites-enabled/wordpress
    state: link
  notify:
    - restart_nginx
  
