---
# - hosts: localhost
#   gather_facts: no
#   roles:
#     - ec2

- hosts: all
  gather_facts: true
  become: true  
  roles:   
    # - server
    # - mysql
    # - wordpress
    # - prometheus
    # - grafanaclear

    - grafana2
