---
- name: delete ec2
  hosts: localhost
  gather_facts: false
  vars:
    aws_region: "us-east-1"
    ec2_action: "start"
    ec2_name: "maged-ansible"

  tasks:
    - name: Get EC2 instance information
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "{{ ec2_name }}"
      register: ec2_info

    - name: Delete EC2 instances
      amazon.aws.ec2_instance:
        region: "{{ aws_region }}"
        instance_ids: "{{ item.instance_id }}"
        state: absent
      loop: "{{ ec2_info.instances }}"
      loop_control:
        label: "{{ item.instance_id }}"
      tags:
        - delete

    - name: Confirm instance deleted
      debug:
        msg: "Instance terminated."

    # - name: Remove IP from inventory after EC2 deletion
    #   hosts: localhost
    #   tasks:
    #     - name: Remove IP from the inventory file
    #       lineinfile:
    #         path: /path/to/inventory.ini
    #         regexp: '^{{ ip_address }}$'
    #         state: absent



